# .streamlit/secrets.toml

[vespa]
url = "https://<host>.vespa-app.cloud/"
public_cert_path = "PATH/data-plane-public-cert.pem"
private_key_path = "PATH/data-plane-private-key.pem"
[api_keys]
llm = "sk-"
tavily = "tvly-"